language: python

python:
  - 2.7
  - 3.5

install:
  - pip install --upgrade pytest coverage codecov
  - python setup.py develop

script:
  - coverage erase
  - coverage run -m pytest

after_success:
  - coverage report
  - codecov
